spring:
  application:
    name: spring-boot-openapi
    jackson:
      property-naming-strategy: SNAKE_CASE
    flyway:
      locations: classpath:/db/migration
      schemas: employee
      baselineOnMigrate: true
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
